name: Tests

on:
    push: ~
    pull_request: ~

jobs:
    phpcs:
        name: PHPCS
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.1
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2, cs2pr

            - run: composer update --no-progress

            - run: vendor/bin/phpcs -q --report=checkstyle src | cs2pr

    phpunit:
        name: PHPUnit on ${{ matrix.php }} ${{ matrix.composer-flags }}
        runs-on: ubuntu-latest
        continue-on-error: ${{ !matrix.stable }}
        strategy:
            matrix:
                php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
                stable: [true]
                coverage: [true]
                composer-flags: ['']
                include:
                    - php: '7.1'
                      stable: true
                      coverage: false
                      composer-flags: '--prefer-lowest'
                    - php: '8.3'
                      stable: false
                      coverage: false
                      composer-flags: '--ignore-platform-req=php+'

        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, mbstring
                  coverage: xdebug
                  tools: composer:v2

            - run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - run: composer update --no-progress ${{ matrix.composer-flags }}

            - run: vendor/bin/simple-phpunit --no-coverage
              if: ${{ !matrix.coverage }}

            - run: vendor/bin/simple-phpunit --coverage-text --coverage-clover=coverage.clover
              if: ${{ matrix.coverage }}

            - run: php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
              if: ${{ matrix.coverage }}

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.1
                  extensions: curl, mbstring
                  coverage: none
                  tools: composer:v2

            - run: composer update --no-progress

            - run: vendor/bin/phpstan analyse --no-progress
